include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    unnecessary_string_interpolations: ignore
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning
  exclude:
    - build/**
    - '**/*.g.dart'

linter:
  rules:
    - prefer_single_quotes
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - avoid_print
    - prefer_const_declarations
    - prefer_final_fields
    - unnecessary_this
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
